fix dev scripts.

diff --git a/dev/fmt b/dev/fmt
--- a/dev/fmt
+++ b/dev/fmt
@@ -2,8 +2,8 @@
 cd "$(dirname "$0")"
 
 if [ "$(docker images -q neko_server_build 2> /dev/null)" == "" ]; then
-	echo "Image 'neko_server_build' not found. Run ./build first."
-	exit 1
+    echo "Image 'neko_server_build' not found. Run ./build first."
+    exit 1
 fi
 
 docker run -it --rm \
